package com.hellguy39.hellweather.core.model

sealed class Language(val code: String) {
    data object Arabic: Language("ar")
    data object Bengali: Language("bn")
    data object Bulgarian: Language("bg")
    data object ChineseSimplified: Language("zh")
    data object ChineseTraditional: Language("zh_tw")
    data object Czech: Language("cs")
    data object Danish: Language("da")
    data object Dutch: Language("nl")
    data object Finnish: Language("fi")
    data object French: Language("fr")
    data object German: Language("de")
    data object Greek: Language("el")
    data object Hindi: Language("hi")
    data object Hungarian: Language("hu")
    data object Italian: Language("it")
    data object Japanese: Language("ja")
    data object Javanese: Language("jv")
    data object Korean: Language("ko")
    data object Mandarin: Language("zh_cmn")
    data object Marathi: Language("mr")
    data object Polish: Language("pl")
    data object Portuguese: Language("pt")
    data object Punjabi: Language("pa")
    data object Romanian: Language("ro")
    data object Russian: Language("ru")
    data object Serbian: Language("sr")
    data object Sinhalese: Language("si")
    data object Slovak: Language("sk")
    data object Spanish: Language("es")
    data object Swedish: Language("sv")
    data object Tamil: Language("ta")
    data object Telugu: Language("te")
    data object Turkish: Language("tr")
    data object Ukrainian: Language("uk")
    data object Urdu: Language("ur")
    data object Vietnamese: Language("vi")
    /* (Shanghainese) */
    data object Wu:	Language("zh_wuu")
    data object Xiang: Language("zh_hsn")
    /* (Cantonese) */
    data object Yue: Language(" zh_yue")
    data object Zulu: Language("zu")
}
